# Version of the data TOML format.
data_config_version=1

[[datasets]]
# Some alphanumeric name (can include spaces and underscores)
name="TCGA_BRCA"
# Optional description
description="Gene expression and clinical data from the TCGA breast cancer (BRCA) study (2012). Gene expression data were downloaded from https://gdc.cancer.gov/about-data/publications/brca_2012 (file BRCA.exp.348.med.txt). Clinical data were obtained from https://www.nature.com/articles/nature11412 (Supp Table 1). Genes with missing data were removed from the gene expression data. Samples with gene expression data were selected from the original clinical data, and samples (rows) were aligned between both files."

# A unique ID. Generate with UUIDs.uuid4()
uuid="20e215cf-1ff9-4cb5-8ed4-a554bd2b654f"

    # Storage location
    [datasets.storage]
    # The name of the storage driver.
    driver="FileSystem"
    # Data stored in FileSystem is either Blob (a file) or BlobTree (a directory/folder)
    type="BlobTree"
    # Path with posix `/` separators.
    # Use @__DIR__ for paths relative to Data.toml
    path="@__DIR__/data/processed/TCGA_BRCA"

[[datasets]]
# Some alphanumeric name (can include spaces and underscores)
name="CCLE"
# Optional description
description="Gene expression and drug sensitivity data from the Cancer Cell Line Encyclopedia. Expression data are from GSE36139 (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE36139; use the Series Matrix File GSE36139-GPL15308_series_matrix.txt). Drug sensitivity data are from Supplementary Table 11 from the CCLE publication (https://www.nature.com/articles/nature11003)."

# A unique ID. Generate with UUIDs.uuid4()
uuid="7bff3b5e-eae7-4ae7-b861-c02565ff294a"

    # Storage location
    [datasets.storage]
    # The name of the storage driver.
    driver="FileSystem"
    # Data stored in FileSystem is either Blob (a file) or BlobTree (a directory/folder)
    type="BlobTree"
    # Path with posix `/` separators.
    # Use @__DIR__ for paths relative to Data.toml
    path="@__DIR__/data/processed/CCLE"

[[datasets]]
# Some alphanumeric name (can include spaces and underscores)
name="Mouse_V1_ALM"
# Optional description
description="Single-cell expression and gene annotation data of cells from the mouse primary visual cortex and anterior lateral motor cortex obtained from the Allen Brain Map (https://portal.brain-map.org/atlases-and-data/rnaseq/mouse-v1-and-alm-smart-seq) with cell clustering annotation from Tasic et al. (2018)(https://doi.org/10.1038/s41586-018-0654-5) (annotation file from the Berens lab github (https://portal.brain-map.org/atlases-and-data/rnaseq/mouse-v1-and-alm-smart-seq)). Genes with non-zero expression (>32 counts) in less than 10 cells have been discarded, following Kobak & Berens (2019) (https://doi.org/10.1038/s41467-019-13056-x)."

# A unique ID. Generate with UUIDs.uuid4()
uuid="10016b00-308e-48cf-a62b-4e18672d7ce6"

    # Storage location
    [datasets.storage]
    # The name of the storage driver.
    driver="FileSystem"
    # Data stored in FileSystem is either Blob (a file) or BlobTree (a directory/folder)
    type="BlobTree"
    # Path with posix `/` separators.
    # Use @__DIR__ for paths relative to Data.toml
    path="@__DIR__/data/processed/Mouse_V1_ALM"